services:
  redis:
    image: redis:7.4.0
    ports:
      - '6379:6379'
  app:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app # Changes in the host directory immediately visible inside the container.
      - /app/node_modules # Avoid overriding node_modules
    depends_on:
      - redis
    # command: node --inspect=0.0.0.0:5000 src/index.js