services:
  app:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app # Changes in the host directory immediately visible inside the container.
      - /app/node_modules # Avoid overriding node_modules