import { PlayerType } from '../types/match.types.js'

export const PLAYER_TYPES: PlayerType[] = ['green', 'blue', 'yellow', 'red']

export const DICE_VALUES = [6, 1, 2, 6, 3, 4, 5, 6]

export const REGEX = Object.freeze({
  EMAIL: /^[\w-\\.]+@([\w-]+\.)+[\w-]{2,4}$/,
  PHONE: /^(\+\d{1,3}[- ]?)?\d{10}$/,
  URL: /^(https?:\/\/)?([\w.-]+)\.([a-zA-Z]{2,})(\/[^\s]*)?(\?[\w%.-]+=[\w%.-]+(&[\w%.-]+=[\w%.-]+)*)?$/,
  MILITARY_TIME: /^(?:[01]\d|2[0-3]):[0-5]\d$/,
  ALPHANUMERIC: /^[A-Za-z0-9]*$/
})

export const INVALID_USERNAMES = [
  'dev',
  'devstore',
  'store',
  'user',
  'profile',
  'sigin',
  'signup',
  'apps',
  'games',
  'websites',
  'settings',
  'about',
  'aboutus',
  'privacy',
  'guest',
  'root',
  'admin',
  'administrator',
  'suppert',
  'system',
  'support',
  'moderator',
  'manager',
  'contact',
  'feedback',
  'info',
  'help',
  'account',
  'service',
  'guestuser',
  'customer',
  'login',
  'logout',
  'password',
  'passwordreset',
  'terms',
  'conditions',
  'termsandconditions',
  'contactus',
  'privacypolicy',
  'auth',
  'authentication',
  'signupform',
  'signinform',
  'sign',
  'signup',
  'signin',
  'login',
  'logout',
  'join',
  'form',
  'main',
  'pricing',
  'project',
  'projects'
]
